import { useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import Footer from '../components/Footer';
import Seo from '../components/Seo';
import './Terms.css';
import './Faq.css';

/* Answers describe how things work, never current totals: a count or percentage
   here would go stale on the next weekly refresh. No FAQPage JSON-LD, same as
   the crawler FAQ in backend/render.py (Google restricted that rich result). */

const Faq = () => {
  const { hash } = useLocation();

  // Professor pages link to /faq#professors. React Router doesn't scroll to a
  // hash, and this runs after App's ScrollToTop, so the jump isn't undone.
  useEffect(() => {
    if (!hash) return;
    document.getElementById(hash.slice(1))?.scrollIntoView();
  }, [hash]);

  return (
    <div className="terms-page">
      <Seo
        title="FAQ — How RateMyHusky Works | RateMyHusky"
        description="Where RateMyHusky's Northeastern professor ratings come from, how rankings work, and how professors can correct or remove their information."
        canonical="https://ratemyhusky.com/faq"
      />
      <main className="terms-main">
        <div className="terms-shell">
          <header className="terms-header">
            <h1>Frequently Asked Questions</h1>
            <p className="terms-meta faq-jump">
              For students: <a href="#students">using the site</a> &middot; For
              professors: <a href="#professors">your page</a>
            </p>
          </header>

          <div className="terms-body">
            <section id="students" className="terms-section faq-group">
              <h2>For students</h2>

              <h3>Where do the ratings and reviews come from?</h3>
              <p>
                Ratings and written reviews come from RateMyProfessors. The Reddit tab on a
                professor's page shows public posts and comments from Northeastern subreddits
                that mention that professor, with a link back to each original. We refresh the
                data every week.
              </p>

              <h3>Is RateMyHusky run by Northeastern?</h3>
              <p>
                No. RateMyHusky is an independent student project. It is not affiliated with,
                endorsed by, or officially connected to Northeastern University or
                RateMyProfessors.
              </p>

              <h3>Can I write a review here?</h3>
              <p>
                Not on RateMyHusky itself. Reviews are collected from RateMyProfessors, so the
                best way to add yours is to post it there. It will show up here after the next
                weekly refresh.
              </p>

              <h3>How are the GOATED Professors ranked?</h3>
              <p>
                By rating and by how many students rated them. A very high score from only a
                few students counts for less than a slightly lower score from hundreds, so the
                list doesn't always go from highest rating to lowest. The ranking compares
                every professor on the same scale and doesn't adjust for how hard their
                department is.
              </p>

              <h3>What does the sentiment bar on a Reddit comment mean?</h3>
              <p>
                It's an automated read of whether that comment speaks about the professor
                positively, negatively, or neutrally. It is generated by a model, not written by
                a person, and it scores each comment on its own, so sarcasm or a comment
                about several professors can be misread. Read the comment itself before you
                rely on the label.
              </p>

              <h3>Why doesn't a professor have a photo?</h3>
              <p>
                We only use photos that Northeastern publishes on its own faculty and college
                directory pages. Many instructors, especially part-time and former faculty,
                don't have one there, so we don't either.
              </p>

              <h3>Why is a course missing from a professor's page?</h3>
              <p>
                A professor's course list shows the courses students have rated them in. A
                course they taught that nobody has reviewed yet won't appear.
              </p>

              <h3>Where do the teaching award badges come from?</h3>
              <p>
                From the award lists Northeastern publishes, including the University
                Excellence in Teaching Award and college awards such as Khoury's. Each badge
                links to the announcement it came from.
              </p>

              <h3>Something on the site is wrong. How do I report it?</h3>
              <p>
                Use the Feedback tab on the left edge of any page (a round button in the
                bottom-right corner on phones) and choose &ldquo;Incorrect Data&rdquo; or
                &ldquo;Missing Data.&rdquo; A link to the page in question helps.
              </p>
            </section>

            <section id="professors" className="terms-section terms-section--last faq-group">
              <h2>For professors</h2>

              <h3>What does RateMyHusky publish about me?</h3>
              <p>
                Your name, department, and college; your ratings and reviews from
                RateMyProfessors; public Reddit comments that mention you; any teaching awards
                Northeastern has announced; and a photo if Northeastern publishes one on its
                directory pages. We publish no contact details and nothing that isn't already
                public in those sources. The full list is in{' '}
                the professors section of our <Link to="/privacy">Privacy Policy</Link>.
              </p>

              <h3>How do you know a request is really from me?</h3>
              <p>
                By your email. Whenever you contact us as a professor, include your
                Northeastern email address. On the feedback form (the Feedback tab on the left
                edge of any page), choose &ldquo;Professor: Correct or Remove My Page&rdquo;; it requires an email. Without one we have no way to tell your request apart from someone else using
                your name, and no way to reply to you. We confirm the request with you at that
                address before we change or remove anything.
              </p>

              <h3>Can I have my page removed?</h3>
              <p>
                Yes, including if you no longer teach at Northeastern. Email{' '}
                <a href="mailto:legal@ratemyhusky.com">legal@ratemyhusky.com</a> from your
                Northeastern address, or use the feedback form, choose
                &ldquo;Professor: Correct or Remove My Page&rdquo;, and enter your Northeastern email. We honor these requests once
                we've confirmed them with you. Your name goes on a removal list that every
                weekly refresh checks, so your page won't come back. We can't remove your data
                from RateMyProfessors or Reddit themselves.
              </p>

              <h3>Something on my page is wrong. Will you fix it?</h3>
              <p>
                Yes. If your photo, department, college, course list, or awards are wrong or
                missing, use the feedback form, choose &ldquo;Professor: Correct or Remove My Page&rdquo;,
                and enter your Northeastern email; or email{' '}
                <a href="mailto:support@ratemyhusky.com">support@ratemyhusky.com</a> from that
                address. For a missing teaching award, include a link to Northeastern's
                announcement of it.
              </p>

              <h3>My page mixes me up with someone else who has the same name.</h3>
              <p>
                Reviews and Reddit comments are matched to professors by name, so two people
                who share a name can end up on one page. Report it the same way, with your
                Northeastern email, and tell us which reviews or comments aren't about you.
                We'll separate the pages or remove what isn't yours.
              </p>

              <h3>Can I get a review taken down?</h3>
              <p>
                Reviews come from RateMyProfessors, so a review you believe breaks their rules
                has to be flagged there. Once RateMyProfessors removes it, it disappears from
                RateMyHusky at the next weekly refresh.
              </p>

              <h3>A Reddit comment on my page is about someone else, or its sentiment label is wrong.</h3>
              <p>
                Tell us through the feedback form (&ldquo;Professor: Correct or Remove My Page&rdquo;) with your
                Northeastern email, a link to your page, and the comment. Reddit comments are
                matched to professors by name, and a comment about someone else is removed from your page. A sentiment label
                that clearly misreads the comment is corrected.
              </p>

              <h3>Can I respond to reviews?</h3>
              <p>
                No. RateMyHusky doesn't host responses to reviews, from professors or anyone
                else.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Faq;
